# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9e607d078b6ca0f196a7e1b208f98715b8d0c1df3b5091fffdb440ab11cf0add9fda8967070157516160eb60985787696d5c47c4e0ef7f99b7df902fae8879d

test:
  secret_key_base: e0c961bbaf311349b9fd1c028b0d9a4a2231b0043b0a720131b67851786b6206af54730aee1e7b40226935eba226fd010fb4b00698f723c9af3ca740eb34d53d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
